---
title: "Cross_validation"
author: "Shun Xie"
date: "2022-11-15"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(modelr)
library(mgcv)
```

# step 1,
cross validation

```{r}
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point()
```
By hand: 

```{r}
train_df = sample_n(nonlin_df,80)
# from the df, not in the original df
test_df = anti_join(nonlin_df, train_df, by='id')
```

```{r}
train_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point()+
  geom_point(data=test_df, color ='red')
```
Let's try to fit three models
```{r}
linear_mod = lm(y~x, data = train_df)

smooth_mod = mgcv::gam(y~s(x),data = train_df)
wiggly_mod = mgcv::gam(y~s(x,k=30), sp=10e-6, data = train_df)

```


```{r}
train_df %>% 
  add_predictions(linear_mod) %>% 
  ggplot(aes(x=x, y=y))+
  geom_point()+
  geom_point(aes(y=pred),color = 'red')
train_df %>% 
  add_predictions(smooth_mod) %>% 
  ggplot(aes(x = x, y = y)) + geom_point() + 
  geom_line(aes(y = pred), color = "red")
train_df %>% 
  add_predictions(wiggly_mod) %>% 
  ggplot(aes(x = x, y = y)) + geom_point() + 
  geom_line(aes(y = pred), color = "red")
```

Let's make predictions and compute RMSEs

```{r}
#test_df %>%  add_predictions(linear_mod)
#root mean square error
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)

```


## can we iterate
```{r}
cv_df = crossv_mc(nonlin_df, 100)

#pull the first column
cv_df %>%  pull(train) %>% .[[1]] %>% as.tibble()
```


```{r}
cv_df = 
  #get the training and testing dataset
  crossv_mc(nonlin_df, 100) %>% 
  mutate(
    train=map(train,as_tibble),
    test=map(test,as_tibble)
  ) %>% 
  mutate(
    linear_fit = map(.x = train, ~lm(y~x,data=.x)),
    smooth_fit = map(.x = train, ~mgcv::gam(y~s(x),data = .x)),
    wiggly_fit = map(.x = train, ~mgcv::gam(y~s(x,k=30),sp=10e-6, data = .x))
  ) %>% 
  mutate(
    rmse_linear = map2_dbl(.x=linear_fit, .y=test, ~rmse(model = .x, data = .y)),
    rmse_smooth = map2_dbl(.x=smooth_fit, .y=test, ~rmse(model = .x, data = .y)),
    rmse_wiggly = map2_dbl(.x=wiggly_fit, .y=test, ~rmse(model = .x, data = .y))
  )
  
```



